name: PR Merge Celebration ­ЪјЅ­ЪїИ

on:
  pull_request:
    types:
      - closed

jobs:
  celebrate-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Send a Super Wholesome Celebration Comment Рюе­Ъјі
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;
            const author = context.payload.pull_request.user.login;

            const messages = [
              "Рюе **Woohoo! Another amazing PR merged!** Рюе\n\n",
              "­Ъњќ **Fantastic work! Your contribution is pure magic!** Рюе­ЪјЕ",
              "­Ъџђ **The codebase is now even stronger thanks to you!** ­Ъњф",
            ];

            const asciiArt = `
            РађРађРађРађРађРађРађРађРађРађРбђРА┤РаќРањРадРБђРађРађРађРађРађРађРађ  
            РађРађРађРађРађРађРађРађРађРбђРАъРаЂРађРађРађРаЎРБдРађРађРађРађРађРађ  
            РађРађРађРађРађРађРађРађРађРАъРађРбђРАђРАђРађРађРаўРАёРађРађРађРађРађ  
            РађРађРађРађРађРађРађРађРбИРАђРађРаўРа┐РаЃРађРађРБђРАЄРађРађРађРађРађ  
            РађРађРађРађРађРађРбђРБаРБЙРАЄРађРађРбђРАаРаъРбЂРА┐РБиРАђРађРађРађРађ  
            РађРађРађРађРБаРБ┤РА┐РаЪРаІРа╗РБёРБђРаѕРаЃРБђРБИРаЃРаўРб┐РБдРБёРађРађ  
            РађРађРбђРАЙРаІРАђРађРађРађРађРађРаЅРаЅРаЅРађРађРађРађРаѕРаЎРб┐РАђРађ  
            РађРађРАъРађРа░РАЄРађРађРађРађРађРађРађРађРађРађРађРађРађРбаРаѕРбиРађ  
            РађРб░РАЄРађРаўРаЃРађРађРађРађРађ­Ъџђ MERGED! ­ЪџђРађРађРађРаўРађРАЙРађ  
            РађРаѕРбДРађРађРађРађРађРађРађРађРађРађРађРађРађРађРађРађРађРА╝РаЂРађ  
            РађРађРаѕРбиРАђРађРађРађРађРађРађРађРађРађРађРађРађРађРбђРАЙРаЂРађРађ  
            РађРађРађРађРаЎРбдРБёРађРађРађРађРађРађРађРађРађРБђРА┤РаІРађРађРађРађ  
            РађРађРађРађРађРађРаЎРа│РадРБёРБђРБђРБђРАцРа┤РаџРаІРађРађРађРађРађРађ  
            `;

            const finalMessage = `
            ­ЪјЅ­ЪјЅ­ЪјЅ **CONGRATULATIONS @${author}!** ­ЪјЅ­ЪјЅ­ЪјЅ  

            ${asciiArt}  

            ${messages.join("\n")}

            ­ЪјХ *We hope you had fun contributing!* ­ЪјХ  
            ­Ъдё **Happy coding!** ­Ъњ╗Рюе  
            `;

            github.rest.issues.createComment({
              owner: repoOwner,
              repo: repoName,
              issue_number: prNumber,
              body: finalMessage
            });
